export default [
    {
        id: 1,
        path: '/features',
        pid: 0,
        menu: 1,
        meta: {
            title: '功能',
        },
        topMenu: true,
        name: 'Features',
        component: 'BaseLayout',
    },
    {
        id: 2,
        path: '/visualization',
        pid: 0,
        menu: 1,
        topMenu: true,
        meta: {
            title: '可视化',
        },
        name: 'Visualization',
        component: 'BaseLayout',
    },
    {
        id: 3,
        path: '/demo',
        pid: 0,
        menu: 1,
        topMenu: true,
        name: 'Demo',
        component: 'BaseLayout',
    },
    {
        id: 4,
        path: '/visualization/d3',
        pid: 2,
        menu: 1,
        topMenu: false,
        meta: {
            title: 'D3图表',
        },
        name: 'D3',
        component: 'defaultLayout',
    },
    {
        id: 5,
        path: '/visualization/d3/chart1',
        pid: 4,
        menu: 1,
        topMenu: false,
        meta: {
            title: 'D3叠加柱状图',
        },
        name: 'D3Charts',
        component: 'Chart1',
    },
    {
        id: 6,
        path: '/demo/drageditor',
        pid: 3,
        menu: 1,
        meta: {
            title: '可视化编辑器',
            icon: 'el-icon-edit-outline',
        },
        topMenu: false,
        name: 'DragEditor',
        component: 'DragEditor',
    },
    {
        id: 7,
        path: '/visualization/echarts',
        pid: 2,
        menu: 1,
        topMenu: false,
        meta: {
            title: 'Echarts',
        },
        name: 'Echarts',
        component: 'defaultLayout',
    },
    {
        id: 8,
        path: '/visualization/echarts/base',
        pid: 7,
        menu: 1,
        topMenu: false,
        meta: {
            title: 'Echarts基础图表',
        },
        name: 'EchartsBase',
        component: 'EchartsBase',
    },
    {
        id: 9,
        path: '/features/table',
        pid: 1,
        menu: 1,
        topMenu: false,
        meta: {
            title: '自定义封装表格',
        },
        name: 'Table',
        component: 'Table',
    },
    {
        id: 10,
        path: '/visualization/three',
        pid: 2,
        menu: 1,
        topMenu: false,
        meta: {
            title: 'Three使用',
        },
        name: 'Three',
        component: 'defaultLayout',
    },
    {
        id: 11,
        path: '/visualization/three/changetexture',
        pid: 10,
        menu: 1,
        topMenu: false,
        meta: {
            title: '家具更换材质',
        },
        name: 'ChangeTexture',
        component: 'ChangeTexture',
    },
    {
        id: 12,
        path: '/visualization/echarts/stock',
        pid: 7,
        menu: 1,
        topMenu: false,
        meta: {
            title: '指数',
        },
        name: 'Stock',
        component: 'Stock',
    },
];
