export default [
    {
        id: 1,
        path: '/features',
        pid: 0,
        menu: 1,
        meta: {
            title: '功能',
        },
        topMenu: true,
        name: 'Features',
        component: 'BaseLayout',
    },
    {
        id: 2,
        path: '/features/lottie',
        pid: 1,
        menu: 1,
        topMenu: false,
        name: 'Lottie',
        meta: {
            title: 'Lottie',
            icon: 'el-icon-football',
        },
        component: 'Lottie',
    },
    {
        id: 3,
        path: '/visualization',
        pid: 0,
        menu: 1,
        topMenu: true,
        meta: {
            title: '可视化',
        },
        name: 'Visualization',
        component: 'defaultLayout',
    },
    {
        id: 4,
        path: '/visualization/echarts',
        pid: 3,
        menu: 1,
        topMenu: false,
        name: 'Echarts',
        meta: {
            title: 'Echarts',
            icon: 'el-icon-football',
        },
        component: 'defaultLayout',
    },
    {
        id: 6,
        path: '/features/table',
        pid: 1,
        menu: 1,
        topMenu: false,
        name: 'custom-table',
        meta: {
            title: '表格',
            icon: 'el-icon-edit-outline',
        },
        component: 'Table',
    },
    {
        id: 7,
        path: '/features/editor',
        pid: 1,
        menu: 1,
        topMenu: false,
        name: 'Editor',
        meta: {
            title: '编辑器',
            icon: 'el-icon-edit',
        },
        component: 'Editor',
    },
    {
        id: 13,
        path: '/features/calendar',
        pid: 1,
        menu: 1,
        topMenu: false,
        name: 'Calendar',
        meta: {
            title: '日历',
            icon: 'el-icon-edit',
        },
        component: 'Calendar',
    },
    {
        id: 8,
        path: '/features/copypaste',
        pid: 1,
        menu: 1,
        topMenu: false,
        name: 'CopyPaste',
        meta: {
            title: '复制粘贴',
            icon: 'el-icon-scissors',
        },
        component: 'CopyPaste',
    },
    {
        id: 9,
        path: '/demo',
        pid: 0,
        menu: 1,
        topMenu: true,
        name: 'Demo',
        component: 'BaseLayout',
    },
    {
        id: 10,
        path: '/features/lazyimg',
        pid: 1,
        menu: 1,
        topMenu: false,
        name: 'LazyImg',
        meta: {
            title: '懒加载',
            icon: 'el-icon-scissors',
        },
        component: 'LazyImg',
    },
    {
        id: 11,
        path: '/features/excel',
        pid: 1,
        menu: 1,
        topMenu: false,
        name: 'Excel',
        meta: {
            title: '表格',
            icon: 'el-icon-menu',
        },
        component: 'Excel',
    },
    {
        id: 14,
        path: '/visualization/scrollanim/anim1',
        pid: 3,
        menu: 1,
        meta: {
            title: '滚动动效',
            icon: 'el-icon-share',
        },
        topMenu: false,
        name: 'ScrollAnim1',
        component: 'ScrollAnim1',
    },
    {
        id: 14,
        path: '/visualization/parallaxanim/anim1',
        pid: 3,
        menu: 1,
        meta: {
            title: '视差动效',
            icon: 'el-icon-share',
        },
        topMenu: false,
        name: 'ParallaxAnim1',
        component: 'ParallaxAnim1',
    },
    {
        id: 15,
        path: '/features/gantt',
        pid: 3,
        menu: 1,
        meta: {
            title: '甘力图',
            icon: 'el-icon-s-ticket',
        },
        topMenu: false,
        name: 'Gantt',
        component: 'Gantt',
    },
    {
        id: 17,
        path: '/demo/drageditor',
        pid: 9,
        menu: 1,
        meta: {
            title: '可视化编辑器',
            icon: 'el-icon-edit-outline',
        },
        topMenu: false,
        name: 'DragEditor',
        component: 'DragEditor',
    },
];
